# Generated by Django 4.1.4 on 2022-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=3)),
                ('number', models.IntegerField(unique=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('use_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('NO', 'Not activated'), ('AC', 'Activated'), ('EX', 'Expired')], default='NO', max_length=2)),
            ],
        ),
    ]
